### ISSUE TITLE
Function not found error

### ISSUE THREAD

**Issue by davidneudorfer** [awslabs/mxnet-lambda#1]
```
➜  mxnet-lambda git:(master) ✗ aws lambda update-function-code --function-name mxnet-lambda --zip-file fileb://lambda_function.zip

An error occurred (ResourceNotFoundException) when calling the UpdateFunctionCode operation: Function not found: arn:aws:lambda:us-east-1:111111111111:function:mxnet-lambda
```

**Comment by hlherrera** [comment]
I had the same error

**Comment by sunilmallya** [comment]
Can you make sure to specify the region correctly?  @davidneudorfer is your default region different than the one where you create the function in the first place?

**Comment by layer4down** [comment]
For others that may encounter this, I found the **Qualifier** dictionary parameter in the Boto3 Lambda call to be hosing me up. Removing it altogether (since I didn't need it) helped my to invoke my Lambda correctly with Boto3.

"Qualifier (string) -- Specify a version or alias to invoke a published version of the function."
